type: one
data_path: "artifacts/data/tron1/trajectory/velocity_gru_explore"
obs_list: [6, 7, 17]        # lin_vel_x(t), lin_vel_y(t), ang_vel_z(t)
command_list: [105, 106, 107]
input_horizon: 10
output_horizon: 1
input_range: 5.0
output_range: 5.0
filter: true
cutoff_freq: 5.0
sample_rate: 50.0
save_path: "artifacts/data/tron1/dataset/one/velocity_policy_gru"
device: "cuda:0"