# Controller Manager configuration
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    tron1_iekf_estimator:
      type: tron1_deploy/Tron1IEKFEstimator

    tron1_velocity_planner:
      type: tron1_deploy/Tron1VelocityPlanner

    tron1_edamp_controller:
      type: humanoid_controllers/HumanoidPassthroughController

    tron1_squatting_controller:
      type: humanoid_controllers/HumanoidPassthroughController

    tron1_standing_controller:
      type: tron1_deploy/Tron1LocoManipulation

    tron1_with_arm_planner:
      type: tron1_deploy/Tron1WithArmPlanner

    tron1_loco_manipulation:
      type: tron1_deploy/Tron1LocoManipulation

tron1_iekf_estimator:
  ros__parameters:
    package_name: "tron1_description"
    urdf_path: "urdf/tron1_with_arm_flat_foot.urdf"
    # prior_noise
    p_init_std: [0.001, 0.001, 0.001]
    v_init_std: [0.001, 0.001, 0.001]
    foot_init_std: 0.001
    orientation_init_std: 0.001
    accel_bias_init_std: 0.000001
    angular_bias_init_std: 0.000001
    # process_noise
    p_process_std: [0.001, 0.001, 0.001]
    accel_input_std: [0.08, 0.08, 0.08] # [0.04, 0.04, 0.04]
    gyro_input_std: [0.02, 0.02, 0.02] # [0.02, 0.02, 0.02]
    accel_bias_process_std: [0.001, 0.001, 0.001]
    angular_bias_process_std: [0.00001, 0.00001, 0.00001]
    # contact_noise
    num_legs: 2
    dim_legs: 4
    contact_names: ["foot_L_Link", "foot_R_Link"]
    # contact_names: ["ankle_L_Link", "ankle_R_Link"]
    using_mob: 1
    using_lo_p: 1 # 1
    using_lo_v: 0
    joint_position_std: [0.05, 0.05, 0.05, 0.05] # [0.05, 0.05, 0.05, 0.05]
    joint_velocity_std: [0.2, 0.2, 0.2, 0.2]
    foot_slide_std: [0.05, 0.05, 0.05] # [0.05, 0.05, 0.05]
    foot_swing_std: [1000.0, 1000.0, 1000.0]
    contact_effort_threshold: 12.0 # 12
    # body_imu calibration
    q_body_imu: [1.0, 0.0, 0.0, 0.0] # [w, x, y, z]
    p_body_imu: [0.0, 0.0, 0.0]
    visualize: 0
    # params
    rate: 500
    N: 1
    # joint order
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"
      - "gripper_joint"
      - "gripper_joint1"
    foot_names:
      - "foot_L"
      - "foot_R"
    foot_sensor_names:
      - "state"
      - "force_x"
      - "force_y"
      - "force_z"
      - "torque_x"
      - "torque_y"
      - "torque_z"
    debug: true

tron1_velocity_planner:
  ros__parameters:
    sampling_frequency: 50.0  # Hz
    damping_frequency: 1.0
    damping_intensity: 0.0
    max_linear_velocity_x: 1.5  # m/s
    max_linear_velocity_y: 1.5  # m/s
    max_angular_velocity_yaw: 1.0  # rad/s
    constant_linear_velocity_x: 0.0  # m/s
    constant_linear_velocity_y: 0.0  # m/s
    constant_angular_velocity_yaw: 0.0  # rad/s
    velocity_x_button: 3
    velocity_y_button: 2
    yaw_rate_button: 1

tron1_edamp_controller:
  ros__parameters:
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"
      # - "gripper_joint"
      # - "gripper_joint1"
    foot_names:
      - "foot_L"
      - "foot_R"
    estimator_name: "tron1_iekf_estimator"
    kd_gains:
      - 3.7639
      - 3.7639
      - 3.7639
      - 0.2463
      - 3.7639
      - 3.7639
      - 3.7639
      - 0.2463
      - 17.4065
      - 17.4065
      - 17.4065
      - 1.3247
      - 1.3247
      - 1.3247
      - 1.3247
      - 1.3247

tron1_squatting_controller:
  ros__parameters:
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"
      - "gripper_joint"
      - "gripper_joint1"
    disable_command_interfaces:
      gripper_joint:
        - "kp"
        - "kd"
      gripper_joint1:
        - "position"
        - "velocity"
        - "effort"
        - "kp"
        - "kd"
    foot_names:
      - "foot_L"
      - "foot_R"
    estimator_name: "tron1_iekf_estimator"
    kp_gains:
      - 70.0
      - 70.0
      - 70.0
      - 70.0
      - 70.0
      - 70.0
      - 70.0
      - 70.0
      - 30.0
      - 30.0
      - 30.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
      - 15.0
    kd_gains:
      - 7.5279
      - 7.5279
      - 7.5279
      - 0.8621
      - 7.5279
      - 7.5279
      - 7.5279
      - 0.8621
      - 8.7032
      - 8.7032
      - 8.7032
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
    joint_pos_ref:
      - 0.0
      - 0.58
      - 1.35
      - -0.8
      - 0.0
      - -0.58
      - -1.35
      - -0.8
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0

tron1_standing_controller:
  ros__parameters:
    update_rate: 50  # Hz
    package_name: "tron1_deploy"
    description_package_name: "tron1_description"
    urdf_path: "urdf/tron1_with_arm_flat_foot.urdf"
    policy_type: "base"
    steer_type: "none"
    history_length: 1
    waypoint_name: "gripper_center"
    ee_frame_name: "gripper_center"
    policy_path: "model/loco-manipulation_standing_policy.onnx"
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"
      - "gripper_joint"
      - "gripper_joint1"
    disable_command_interfaces:
      gripper_joint:
        - "kp"
        - "kd"
      gripper_joint1:
        - "position"
        - "velocity"
        - "effort"
        - "kp"
        - "kd"
    foot_names:
      - "foot_L"
      - "foot_R"
    estimator_name: "tron1_iekf_estimator"
    planner_name: "tron1_with_arm_planner"
    joint_pos_ref:
      - 0.0
      - 0.58
      - 1.35
      - -0.8
      - 0.0
      - -0.58
      - -1.35
      - -0.8
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    kp_gains:
      - 68.74873767158742
      - 68.74873767158742
      - 68.74873767158742
      - 23.696920165660938
      - 68.74873767158742
      - 68.74873767158742
      - 68.74873767158742
      - 23.696920165660938
      - 13.6710
      - 13.6710
      - 13.6710
      - 6.936180319809881
      - 6.936180319809881
      - 6.936180319809881
      - 6.936180319809881
      - 6.936180319809881
    kd_gains:
      - 4.3766805728295495
      - 4.3766805728295495
      - 4.3766805728295495
      - 0.4310265120602001
      - 4.3766805728295495
      - 4.3766805728295495
      - 4.3766805728295495
      - 0.4310265120602001
      - 8.7032
      - 8.7032
      - 8.7032
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
    action_scales:
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.21099788348215265
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.21099788348215265
      - 0.5486053914746988
      - 0.5486053914746988
      - 0.5486053914746988
      - 0.3243860303882169
      - 0.3243860303882169
      - 0.3243860303882169
      - 1.2512032600688365
    debug: true

tron1_with_arm_planner:
  ros__parameters:
    update_rate: 50  # Hz
    package_name: "tron1_description"
    urdf_path: "urdf/tron1_with_arm_flat_foot.urdf"
    waypoint_names:
      - "gripper_center"
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"
      - "gripper_joint"
      - "gripper_joint1"
    foot_names:
      - "foot_L"
      - "foot_R"
    ref_planner_name: "tron1_velocity_planner"
    estimator_name: "tron1_iekf_estimator"
    point_pos_b: [0.4, 0.1, 0.25]
    point_rpy_b: [0.0, 0.0, 0.0]
    use_circle_trajectory: true
    circle_start_button: 4
    circle_radius: 0.06 # 0.05
    circle_frequency: 0.05 # 0.2
    circle_phase: 0.0
    use_meta_dynamics: true
    node_name: "tron1_mppi_planner_node"
    dt: 0.02
    horizon: 8
    subscribe_topic_name: "tron1/mppi_command"
    publish_topic_name: "tron1/mppi_obs"
    debug: true

tron1_loco_manipulation:
  ros__parameters:
    update_rate: 50  # Hz
    package_name: "tron1_deploy"
    description_package_name: "tron1_description"
    urdf_path: "urdf/tron1_with_arm_flat_foot.urdf"
    policy_type: "base"
    steer_type: "none"
    history_length: 1
    waypoint_name: "gripper_center"
    ee_frame_name: "gripper_center"
    policy_path: "model/loco-manipulation_policy.onnx"
    joint_names:
      - "abad_L_Joint"
      - "hip_L_Joint"
      - "knee_L_Joint"
      - "ankle_L_Joint"
      - "abad_R_Joint"
      - "hip_R_Joint"
      - "knee_R_Joint"
      - "ankle_R_Joint"
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"
      - "gripper_joint"
      - "gripper_joint1"
    disable_command_interfaces:
      gripper_joint:
        - "kp"
        - "kd"
      gripper_joint1:
        - "position"
        - "velocity"
        - "effort"
        - "kp"
        - "kd"
    foot_names:
      - "foot_L"
      - "foot_R"
    estimator_name: "tron1_iekf_estimator"
    planner_name: "tron1_with_arm_planner"
    kp_gains:
      - 68.74873767158742
      - 68.74873767158742
      - 68.74873767158742
      - 23.696920165660938
      - 68.74873767158742
      - 68.74873767158742
      - 68.74873767158742
      - 23.696920165660938
      - 13.6710
      - 13.6710
      - 13.6710
      - 6.936180319809881
      - 6.936180319809881
      - 6.936180319809881
      - 412.77350637889003
      - 412.77350637889003
    kd_gains:
      - 4.3766805728295495
      - 4.3766805728295495
      - 4.3766805728295495
      - 0.4310265120602001
      - 4.3766805728295495
      - 4.3766805728295495
      - 4.3766805728295495
      - 0.4310265120602001
      - 8.7032
      - 8.7032
      - 8.7032
      - 0.4415709536424074
      - 0.4415709536424074
      - 0.4415709536424074
      - 131.3898878389041
      - 131.3898878389041
    action_scales:
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.21099788348215265
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.1309114945934423
      - 0.21099788348215265
      - 0.5486053914746988
      - 0.5486053914746988
      - 0.5486053914746988
      - 0.3243860303882169
      - 0.3243860303882169
      - 0.3243860303882169
      - 1.2512032600688365
    debug: true
